// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDKX_1h-B83NYYOpRnrcst2lHzAffA2I',
    appId: '1:839636053960:web:9ea3403864d9d739119afd',
    messagingSenderId: '839636053960',
    projectId: 'user-note',
    authDomain: 'user-note.firebaseapp.com',
    storageBucket: 'user-note.appspot.com',
    measurementId: 'G-ZPDNNS8PBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3Z6X2Zy4JAFFZrWz3Vj_Ov2VtFdjDeM',
    appId: '1:839636053960:android:312fc9afe59d8c6d119afd',
    messagingSenderId: '839636053960',
    projectId: 'user-note',
    storageBucket: 'user-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8vZFiFSDbzfPiQgm-ph7v8vMz5pP7crE',
    appId: '1:839636053960:ios:440eb1967130e243119afd',
    messagingSenderId: '839636053960',
    projectId: 'user-note',
    storageBucket: 'user-note.appspot.com',
    iosBundleId: 'com.example.fireBaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8vZFiFSDbzfPiQgm-ph7v8vMz5pP7crE',
    appId: '1:839636053960:ios:440eb1967130e243119afd',
    messagingSenderId: '839636053960',
    projectId: 'user-note',
    storageBucket: 'user-note.appspot.com',
    iosBundleId: 'com.example.fireBaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEDKX_1h-B83NYYOpRnrcst2lHzAffA2I',
    appId: '1:839636053960:web:c7ea0ed2beb3a052119afd',
    messagingSenderId: '839636053960',
    projectId: 'user-note',
    authDomain: 'user-note.firebaseapp.com',
    storageBucket: 'user-note.appspot.com',
    measurementId: 'G-0JVW027RQY',
  );
}
